config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get 'about' => 'welcome#about'
  get 'start' => 'welcome#start'
  get 'start/beachclean' => 'welcome#start_beachclean'
  get 'start/whalewatch' => 'welcome#start_whalewatch'
  get 'start/fisheries'  => 'welcome#start_fisheries'
  get 'delete' => 'welcome#delete'

  get  'contact' => 'messages#new'
  post 'contact' => 'messages#create', :as => :create_message

  # Logging data

  resources :activities, only: [:index]

  resources :beachcleans, only: [:new, :show, :create, :destroy], param: :uuid do
    get  :summary, :controller => 'beachcleans', :action => 'summary'
    post :sign,    :controller => 'beachcleans', :action => 'sign'
    post :submit,  :controller => 'beachcleans', :action => 'submit'
    get  :thanks,  :controller => 'beachcleans', :action => 'thanks'
  end

  resources :whalewatches, only: [:new, :show, :create, :destroy], param: :uuid do
    # TODO analogous to beachcleans
  end

  resources :fisheries, only: [:new, :show, :create, :destroy], param: :uuid do
    # TODO analogous to beachcleans
  end

  # Analytics

  # TODO
  # get  'analytics'       => 'analytics#start'
  # post 'analytics/query' => 'analytics#query'
end

app/models/message.rb
class Message
  include ActiveModel::Model

  attr_accessor :name, :email, :text, :timestamp
  validates :name, :email, :text, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.with(message: @message).forward.deliver

      flash[:success] = 'Thanks! We got your message.'
      redirect_to contact_path
    else
      flash[:error] = 'Please make sure to fill in all fields.'
      render :new
    end
  end

  private

  def message_params
    params.fetch(:message, {})
          .permit(:name, :email, :text)
          .merge({ timestamp: Time.now })
  end
end

app/views/messages/new.html.haml
%h3 Send us a message

- if flash[:error]
  = flash[:error]

- if flash[:success]
  = flash[:success]

= form_for @message, :url => create_message_path(@message) do |form|

  = form.label :name, 'Name'
  = form.text_field :name

  = form.label :email, 'Email address'
  = form.email_field :email

  = form.label :text, 'Message'
  = form.text_area :text

  = form.submit 'Send'

%h3 Drop by

%p
  We work together with
  %strong Jay's Pro Dive Center
  at Guinjata Bay.
  You'll often find us at their dive center, planning a dive,
  analysing data we collected, discussing observations and strategies,
  or simply having a break, enjoying the priviledge to work in a place like this.

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3642.91261634257!2d35.49172751537393!3d-24.069381584433124!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1f1f612787f6a713%3A0xf0c669d7b17271e0!2sJay&#39;s+Pro+Dive+Centre!5e0!3m2!1sen!2sde!4v1544425168370" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>