config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get 'about' => 'welcome#about'
  get 'start' => 'welcome#start'
  get 'start/beachclean' => 'welcome#start_beachclean'
  get 'start/whalewatch' => 'welcome#start_whalewatch'
  get 'start/fisheries'  => 'welcome#start_fisheries'
  get 'delete' => 'welcome#delete'

  get  'contact' => 'messages#new'
  post 'contact' => 'messages#create', :as => :create_message

  # Logging data

  resources :activities, only: [:index]

  resources :beachcleans, only: [:new, :show, :create, :destroy], param: :uuid do
    get  :summary, :controller => 'beachcleans', :action => 'summary'
    post :sign,    :controller => 'beachcleans', :action => 'sign'
    post :submit,  :controller => 'beachcleans', :action => 'submit'
    get  :thanks,  :controller => 'beachcleans', :action => 'thanks'
  end

  resources :whalewatches, only: [:new, :show, :create, :destroy], param: :uuid do
    # TODO analogous to beachcleans
  end

  resources :fisheries, only: [:new, :show, :create, :destroy], param: :uuid do
    # TODO analogous to beachcleans
  end

  # Analytics

  # TODO
  # get  'analytics'       => 'analytics#start'
  # post 'analytics/query' => 'analytics#query'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def start
  end

  def start_beachclean
  end

  def start_whalewatch
  end

  def start_fisheries
  end

  def delete
  end
end

app/views/welcome/about.html.haml
%p
  We are
  %strong Love The Oceans (LTO),
  a non-profit marine conservation organisation working in Guinjata Bay, Mozambique.

%p
  %a.start{ 'href' => 'https://lovetheoceans.org' }
    Check out our website.

%p
  %strong Guinjata Bay,
  whilst home to a huge host of marine life, has never been studied in depth for any prolonged amount of time.
  We hope to protect and study the diverse marine life found here, including many species of sharks, rays and
  the famous humpback whales. We use research, education and diving to drive action towards a more sustainable future.

%p
  Our ultimate goal is to establish a Marine Protected Area for the Inhambane Province in Mozambique,
  achieving higher biodiversity whilst protecting endangered species.

%p
  %a.start{ 'href' => '/start' }
    And you can help!

%p
  Questions? Want to get involved?
  %a.start{ 'href' => '/contact' }
    Get in touch!

app/views/welcome/contact.html.haml
%h3 Send us a message

Coming soon.

%h3 Drop by and say Hello

%p
  We work together with
  %strong Jay's Pro Dive Center
  at Guinjata Bay.
  You'll often find us at their dive center, planning a dive,
  analysing data we collected, discussing observations and strategies,
  or simply having a break, enjoying the priviledge to work in a place like this.

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3642.91261634257!2d35.49172751537393!3d-24.069381584433124!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1f1f612787f6a713%3A0xf0c669d7b17271e0!2sJay&#39;s+Pro+Dive+Centre!5e0!3m2!1sen!2sde!4v1544425168370" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/welcome/delete.html.haml
%h3 Delete all data

%p
  This website stores your logs and some of the pages in a local cache in your browser,
  in order to allow you to use most parts of it offline without losing data.

%p
  If you don't want any data to be stored in your browser anymore, we will delete it for you.

%p
  %strong Just be aware that you will lose all unsubmitted logs.

  %a.start{ 'href' => '/activities' }
    Check unsubmitted logs

%button.delete{ id: 'js-delete-data' } Delete all browser data

app/views/welcome/home.html.haml
%p
  = link_to start_path do
    %img{ src: '/images/info_icon.png', class: 'icon' }
    How to get started

%p
  %br

%p
  = link_to new_beachclean_path do
    %img{ src: '/images/beachclean_icon.png', class: 'icon' }
    New beach clean

%p
  = link_to new_whalewatch_path do
    %img{ src: '/images/whalewatch_icon.png', class: 'icon' }
    New whale watch

%p
  = link_to new_fishery_path do
    %img{ src: '/images/fisheries_icon.png', class: 'icon' }
    New fisheries data

%p
  %br

%p
  = link_to activities_path do
    %img{ src: '/images/unsubmitted_icon.png', class: 'icon' }
    Unsubmitted logs
    %span{ id: 'unsubmitted-logs-count' }

%p
  = link_to delete_path do
    %img{ src: '/images/delete_icon.png', class: 'icon' }
    Delete all data

-# TODO Only when logged in:
-# %p
-#   = link_to analytics_path do
-#     %img{ src: '/images/analytics_icon.png', class: 'icon' }
-#     Analytics

-# TODO
-# small: Log in as LTO staff or volunteer

app/views/welcome/start.html.haml
%h3 Olá, beach hero!

%p
  We're happy to see you here.
  Want to get involved in saving the oceans?

%p
  As a marine conservation organisation, we collect and analyse data,
  in order to back our decisions and make a strong case for our arguments.
  That's where we need your support!

%h3 How you can help

%p
  %ul.bullets
    %li
      You're going for a walk along the beach and notice all the garbage that's
      been left behind or washed ashore?
      It's never been easier to help: Bring an old bag and collect what you find.

      %a.start{ 'href' => '/start/beachclean' }
        How to log a beach clean

    %li
      You're on a whale watching or snorkeling trip and encounter humpback whales,
      whale sharks, or manta rays?
      Let us know!

      %a.start{ 'href' => '/start/whalewatch' }
        How to log megafauna sightings

    %li
      You stroll along the beach and see local fishermen bringing in their catch of the day?
      You always wanted to get to know the local culture a bit more? This is your chance!

      %a.start{ 'href' => '/start/fisheries' }
        How to log catches of the local fishermen

app/views/welcome/start_beachclean.html.haml
%p
  Since May 2017 we have removed over 500 kg of marine debris
  from a 15 km stretch of coastline. While some is local,
  the vast majority is transported to the area via ocean currents,
  highlighting the global nature of marine pollution.

%h3 Be part of the cure!

%p
  Bring along an old bag and collect garbage you find on the beach.

%p
  Take this app with you to log what you find. We use internationally
  recognised categories, so we can analyse and compare marine debris
  by type and weight all around the world.

%p
  Afterwards, dispose the collected waste where it belongs.

%h3 Tips

%ul.bullets
  %li
    Although you could do the logging afterwards, it's often easiest to log items
    directly when picking them up.

  %li
    You don't need a network connection in order to do this.
    When you're offline, logged data is stored on your device.
    You can submit it later.

%p
  Ready to rumble?
  %a.start{ 'href' => new_beachclean_path }
    Start beach clean

app/views/welcome/start_fisheries.html.haml
%p
  We are happy to have built a relationship of mutual respect with the local fishermen
  in Guinjata and Paindane, which allows us to study what and how much they catch.
  Our long-term goal is to support them in sustainable fishing that benefits
  both the fishermen and the marine ecosystem.

%h3 What to log

%p
  In order to measure the effect and sustainability of the local fishing,
  we need to know how what kind of fish was caught, how many specimen,
  and with which method of fishing.
  We can use this data in research publications only if we have pictures
  of all the logged fish.

%p
  Approach the fishermen and kindly ask whether they let you take a picture of their catch.
  If you're friendly and respectful, you'll find that the locals are very cooperative
  and open to a nice chat.
  Note, however, that this often involves touching or moving the fish.

%h3 Tips on interacting with the local fishermen

%ul.bullets
  %li
    Don't judge.
    For the fishermen, their work is the only way to feed their families.
  %li
    If you feel disgusted or sad at the sight of dead or dying fish,
    politely retreat.

%p
  Questions? Unsure about something? Or want to share an encounter?
  %a.start{ 'href' => '/contact' }
    Get in touch!

%p
  Ready for action?
  %a.start{ 'href' => new_fishery_path }
    Log fisheries data

app/views/welcome/start_whalewatch.html.haml
%p
  There's a few information we need in order to be able to use observations
  of humpback whales, whale sharks and manta rays in our research.

  %ul.bullets
    %li
      Location of the boat, as well as distance and direction of the animals from the boat
    %li
      Environmental conditions (in particular sea state and cloud cover)
    %li
      Number of individuals
    %li
      Behaviour

%h3 Location

%p
  If you're connected to a network, we can grab your GPS location.
  Otherwise simply ask the skipper of your boat (he has a GPS on board and can tell you).

%h3 Behaviour

Coming soon.

%h3 Pictures

%p
  If you're taking pictures, either from the boat or snorkeling, that's great!
  Here's the kind of shots that can help us identify individuals:

  %ul.bullets
    %li Humpback whales: ...
    %li Whale sharks: ...
    %li Manta rays: ...
    %li Turtles and others: Just as many pictures as possible ;-)

%h3 Code of conduct

%p
  When snorkeling with megafauna, please make sure to
  %strong never touch
  the animals.

%p
  Ready to rumble?
  %a.start{ 'href' => new_whalewatch_path }
    Log a sighting